name: Py35
dependencies:
- alabaster=0.7.6=py35_0
- appnope=0.1.0=py35_0
- babel=2.1.1=py35_0
- biopython=1.65=np110py35_0
- bokeh=0.11.1=py35_0
- certifi=14.05.14=py35_0
- cycler=0.9.0=py35_0
- decorator=4.0.6=py35_0
- docutils=0.12=py35_0
- flask=0.10.1=py35_1
- freetype=2.5.5=0
- ipykernel=4.1.1=py35_0
- ipython=4.0.1=py35_0
- ipython-notebook=4.0.4=py35_0
- ipython-qtconsole=4.0.1=py35_0
- ipython_genutils=0.1.0=py35_0
- itsdangerous=0.24=py35_0
- jbig=2.1=0
- jedi=0.9.0=py35_0
- jinja2=2.8=py35_0
- jpeg=8d=1
- jsonschema=2.4.0=py35_0
- jupyter_client=4.1.1=py35_0
- jupyter_core=4.0.6=py35_0
- libpng=1.6.17=0
- libsodium=0.4.5=0
- libtiff=4.0.6=1
- markupsafe=0.23=py35_0
- matplotlib=1.5.1=np110py35_0
- mistune=0.7.1=py35_0
- mkl=11.3.1=0
- nbconvert=4.0.0=py35_0
- nbformat=4.0.1=py35_0
- networkx=1.11=py35_0
- notebook=4.0.6=py35_0
- numpy=1.10.4=py35_0
- openssl=1.0.2f=0
- pandas=0.17.0=np110py35_0
- path.py=8.1.2=py35_1
- pep8=1.6.2=py35_0
- pexpect=3.3=py35_0
- pickleshare=0.5=py35_0
- pillow=3.1.1=py35_0
- pip=8.0.2=py35_0
- psutil=3.3.0=py35_0
- ptyprocess=0.5=py35_0
- pyflakes=1.0.0=py35_0
- pygments=2.0.2=py35_0
- pyparsing=2.0.3=py35_0
- pyqt=4.11.4=py35_1
- python=3.5.1=0
- python-dateutil=2.4.2=py35_0
- python.app=1.2=py35_4
- pytz=2015.7=py35_0
- pyyaml=3.11=py35_1
- pyzmq=15.1.0=py35_0
- qt=4.8.7=1
- qtconsole=4.1.1=py35_0
- readline=6.2=2
- requests=2.9.1=py35_0
- rope=0.9.4=py35_1
- scikit-image=0.11.3=np110py35_0
- scipy=0.17.0=np110py35_0
- setuptools=19.6.2=py35_0
- simplegeneric=0.8.1=py35_0
- sip=4.16.9=py35_0
- six=1.10.0=py35_0
- snakemake=3.5.5=py35_1
- snowballstemmer=1.2.0=py35_0
- sphinx=1.3.1=py35_0
- sphinx_rtd_theme=0.1.7=py35_0
- spyder=2.3.8=py35_0
- spyder-app=2.3.8=py35_0
- sqlite=3.9.2=0
- terminado=0.5=py35_0
- tk=8.5.18=0
- tornado=4.3=py35_0
- traitlets=4.0.0=py35_0
- werkzeug=0.10.4=py35_0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- yaml=0.1.6=0
- zeromq=4.1.3=0
- zlib=1.2.8=0
- pip:
  - ipython-genutils==0.1.0
  - jupyter-client==4.1.1
  - jupyter-core==4.0.6
  - rope-py3k==0.9.4.post1
  - sphinx-rtd-theme==0.1.7

